version: '3'

services: 
 
    app:
        image: gilangvperdana/moodle
        ports: 
            - "9992:80" 
        restart: always 
        networks: 
            - web
        volumes:
            - "./data/moodledata:/var/www/html/moodledata"
 
networks:
  web:
    external: true
